obj-y += __tm_to_time.o
obj-y += __time_to_tm.o
obj-y += mktime.o
obj-y += ctime.o
obj-y += strftime.o
obj-y += asctime.o
obj-y += gmtime.o
obj-y += gettimeofday.o
obj-y += localtime.o
obj-y += time.o
obj-y += difftime.o
obj-y += clock.o
 
