# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_SELFTEST_STRING_MEMCMP)    += memcmp.o
obj-$(CONFIG_SELFTEST_STRING_MEMCPY)    += memcpy.o
obj-$(CONFIG_SELFTEST_STRING_MEMMOVE)   += memmove.o
obj-$(CONFIG_SELFTEST_STRING_MEMSET)    += memset.o
