# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += core/
obj-$(CONFIG_GPIO_GENERIC) += generic.o
obj-$(CONFIG_GPIO_INTEL_ICH) += intel-ich.o
obj-$(CONFIG_GPIO_PARALLEL) += parallel.o
obj-$(CONFIG_GPIO_PCF8574) += pcf8574.o
