/* SPDX-License-Identifier: GPL-2.0-or-later */
#include <ctype.h>
#include <ascii.h>
#include <export.h>

const unsigned short ctype_table[256] = {
    [ASCII_NUL] = CTYPE_CNTRL,
    [ASCII_SOH] = CTYPE_CNTRL,
    [ASCII_STX] = CTYPE_CNTRL,
    [ASCII_ETX] = CTYPE_CNTRL,
    [ASCII_EOT] = CTYPE_CNTRL,
    [ASCII_ENQ] = CTYPE_CNTRL,
    [ASCII_ACK] = CTYPE_CNTRL,
    [ASCII_BEL] = CTYPE_CNTRL,
    [ASCII_BS ] = CTYPE_CNTRL,
    [ASCII_HT ] = CTYPE_CNTRL | CTYPE_SPACE,
    [ASCII_LF ] = CTYPE_CNTRL | CTYPE_SPACE,
    [ASCII_VT ] = CTYPE_CNTRL | CTYPE_SPACE | CTYPE_BLANK,
    [ASCII_FF ] = CTYPE_CNTRL | CTYPE_SPACE,
    [ASCII_CR ] = CTYPE_CNTRL | CTYPE_SPACE,
    [ASCII_SO ] = CTYPE_CNTRL,
    [ASCII_SI ] = CTYPE_CNTRL,
    [ASCII_DLE] = CTYPE_CNTRL,
    [ASCII_DC1] = CTYPE_CNTRL,
    [ASCII_DC2] = CTYPE_CNTRL,
    [ASCII_DC3] = CTYPE_CNTRL,
    [ASCII_DC4] = CTYPE_CNTRL,
    [ASCII_NAK] = CTYPE_CNTRL,
    [ASCII_SYN] = CTYPE_CNTRL,
    [ASCII_ETB] = CTYPE_CNTRL,
    [ASCII_CAN] = CTYPE_CNTRL,
    [ASCII_EM ] = CTYPE_CNTRL,
    [ASCII_SUB] = CTYPE_CNTRL,
    [ASCII_ESC] = CTYPE_CNTRL,
    [ASCII_FS ] = CTYPE_CNTRL,
    [ASCII_GS ] = CTYPE_CNTRL,
    [ASCII_RS ] = CTYPE_CNTRL,
    [ASCII_US ] = CTYPE_CNTRL,

    [' ' ] = CTYPE_SPACE | CTYPE_HDSPA | CTYPE_BLANK,
    ['!' ] = CTYPE_PUNCT,
    ['"' ] = CTYPE_PUNCT,
    ['#' ] = CTYPE_PUNCT,
    ['$' ] = CTYPE_PUNCT,
    ['%' ] = CTYPE_PUNCT,
    ['&' ] = CTYPE_PUNCT,
    ['\''] = CTYPE_PUNCT,
    ['(' ] = CTYPE_PUNCT,
    [')' ] = CTYPE_PUNCT,
    ['*' ] = CTYPE_PUNCT,
    ['+' ] = CTYPE_PUNCT,
    [',' ] = CTYPE_PUNCT,
    ['-' ] = CTYPE_PUNCT,
    ['.' ] = CTYPE_PUNCT,
    ['/' ] = CTYPE_PUNCT,

    ['0'] = CTYPE_DIGIT,
    ['1'] = CTYPE_DIGIT,
    ['2'] = CTYPE_DIGIT,
    ['3'] = CTYPE_DIGIT,
    ['4'] = CTYPE_DIGIT,
    ['5'] = CTYPE_DIGIT,
    ['6'] = CTYPE_DIGIT,
    ['7'] = CTYPE_DIGIT,
    ['8'] = CTYPE_DIGIT,
    ['9'] = CTYPE_DIGIT,

    [':'] = CTYPE_PUNCT,
    [';'] = CTYPE_PUNCT,
    ['<'] = CTYPE_PUNCT,
    ['='] = CTYPE_PUNCT,
    ['>'] = CTYPE_PUNCT,
    ['?'] = CTYPE_PUNCT,
    ['@'] = CTYPE_PUNCT,

    ['A'] = CTYPE_UPPER | CTYPE_HEXDG,
    ['B'] = CTYPE_UPPER | CTYPE_HEXDG,
    ['C'] = CTYPE_UPPER | CTYPE_HEXDG,
    ['D'] = CTYPE_UPPER | CTYPE_HEXDG,
    ['E'] = CTYPE_UPPER | CTYPE_HEXDG,
    ['F'] = CTYPE_UPPER | CTYPE_HEXDG,
    ['G'] = CTYPE_UPPER,
    ['H'] = CTYPE_UPPER,
    ['I'] = CTYPE_UPPER,
    ['J'] = CTYPE_UPPER,
    ['K'] = CTYPE_UPPER,
    ['L'] = CTYPE_UPPER,
    ['M'] = CTYPE_UPPER,
    ['N'] = CTYPE_UPPER,
    ['O'] = CTYPE_UPPER,
    ['P'] = CTYPE_UPPER,
    ['Q'] = CTYPE_UPPER,
    ['R'] = CTYPE_UPPER,
    ['S'] = CTYPE_UPPER,
    ['T'] = CTYPE_UPPER,
    ['U'] = CTYPE_UPPER,
    ['V'] = CTYPE_UPPER,
    ['W'] = CTYPE_UPPER,
    ['X'] = CTYPE_UPPER,
    ['Y'] = CTYPE_UPPER,
    ['Z'] = CTYPE_UPPER,

    ['[' ] = CTYPE_PUNCT,
    ['\\'] = CTYPE_PUNCT,
    [']' ] = CTYPE_PUNCT,
    ['^' ] = CTYPE_PUNCT,
    ['_' ] = CTYPE_PUNCT,
    ['`' ] = CTYPE_PUNCT,

    ['a'] = CTYPE_LOWER | CTYPE_HEXDG,
    ['b'] = CTYPE_LOWER | CTYPE_HEXDG,
    ['c'] = CTYPE_LOWER | CTYPE_HEXDG,
    ['d'] = CTYPE_LOWER | CTYPE_HEXDG,
    ['e'] = CTYPE_LOWER | CTYPE_HEXDG,
    ['f'] = CTYPE_LOWER | CTYPE_HEXDG,
    ['g'] = CTYPE_LOWER,
    ['h'] = CTYPE_LOWER,
    ['i'] = CTYPE_LOWER,
    ['j'] = CTYPE_LOWER,
    ['k'] = CTYPE_LOWER,
    ['l'] = CTYPE_LOWER,
    ['m'] = CTYPE_LOWER,
    ['n'] = CTYPE_LOWER,
    ['o'] = CTYPE_LOWER,
    ['p'] = CTYPE_LOWER,
    ['q'] = CTYPE_LOWER,
    ['r'] = CTYPE_LOWER,
    ['s'] = CTYPE_LOWER,
    ['t'] = CTYPE_LOWER,
    ['u'] = CTYPE_LOWER,
    ['v'] = CTYPE_LOWER,
    ['w'] = CTYPE_LOWER,
    ['x'] = CTYPE_LOWER,
    ['y'] = CTYPE_LOWER,
    ['z'] = CTYPE_LOWER,

    ['{'] = CTYPE_PUNCT,
    ['|'] = CTYPE_PUNCT,
    ['}'] = CTYPE_PUNCT,
    ['~'] = CTYPE_PUNCT,
    [127] = CTYPE_CNTRL,
};
EXPORT_SYMBOL(ctype_table);
