include-y += $(obj)include/

obj-$(CONFIG_ACPI_DEBUG) += debugger/
obj-y += dispatcher/
obj-y += events/
obj-y += executer/
obj-y += hardware/
obj-y += namespace/
obj-y += parser/
obj-y += resources/
obj-y += tables/
obj-y += utilities/
obj-y += osd.o
