# SPDX-License-Identifier: GPL-2.0-or-later
include-y += include/
obj-y += dispatcher/ events/ executer/
obj-y += hardware/ namespace/ parser/
obj-y += resources/ tables/ utilities/
obj-$(CONFIG_ACPI_DEBUG) += debugger/
obj-y += osd.o
