# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += delay.o iomem.o iodelay.o
obj-$(CONFIG_ARCH_X86_32) += string32.o strstr32.o memcpy32.o
obj-$(CONFIG_ARCH_X86_32) += setjmp32.o kcontext32.o
obj-$(CONFIG_ARCH_X86_64) += setjmp64.o kcontext64.o
