# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += page.o

# CPU model
obj-$(CONFIG_CPU_ARM926) += proc-arm926.o

# Cache model
obj-$(CONFIG_CPU_CACHE_V4WT) += cache-v4wt.o
obj-$(CONFIG_CPU_CACHE_V7) += cache-v7.o

# TLB model
obj-$(CONFIG_CPU_TLB_V4WBI) += tlb-v4wbi.o
obj-$(CONFIG_CPU_TLB_V7) += tlb-v7.o
