# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_SELFTEST_MEMORY_BUDDY)     += buddy.o
obj-$(CONFIG_SELFTEST_MEMORY_IOREMAP)   += ioremap.o
obj-$(CONFIG_SELFTEST_MEMORY_KCACHE)    += kcache.o
obj-$(CONFIG_SELFTEST_MEMORY_KMALLOC)   += kmalloc.o
obj-$(CONFIG_SELFTEST_MEMORY_MEMPOOL)   += mempool.o
obj-$(CONFIG_SELFTEST_MEMORY_VMALLOC)   += vmalloc.o
obj-$(CONFIG_SELFTEST_MEMORY_VMEM)      += vmem.o
