# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += bus.o device.o driver.o
obj-y += init.o devid.o
obj-y += devres.o devres-lib.o
obj-y += platform.o base.o fwnode.o
obj-$(CONFIG_ACPI) += platform-acpi.o
obj-$(CONFIG_DT) += platform-dt.o
obj-$(CONFIG_ISA_BUS) += isa.o
