# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += bus.o device.o driver.o
obj-y += init.o devres.o devid.o
obj-y += platform.o base.o

obj-$(CONFIG_ACPI) += platform-acpi.o
obj-$(CONFIG_DT) += platform-dt.o
