# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += core/

obj-$(CONFIG_POWER_HISI) += hisi.o
obj-$(CONFIG_POWER_PIIX) += piix.o
obj-$(CONFIG_POWER_PIIX4) += piix4.o
obj-$(CONFIG_POWER_SYSCON) += syscon.o
