# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += core/
obj-$(CONFIG_POWER_CE4100) += ce4100.o
obj-$(CONFIG_POWER_CS5530A) += cs5530a.o
obj-$(CONFIG_POWER_CS5536) += cs5536.o
obj-$(CONFIG_POWER_PIIX) += piix.o
obj-$(CONFIG_POWER_PIIX4) += piix4.o
obj-$(CONFIG_POWER_RDC321X) += rdc321x.o
