obj-y += boot/ lib/ mm/
obj-y += entry.o
obj-y += setup.o
obj-y += power.o
obj-y += proc.o
obj-y += syscall.o

obj-y += irq.o
obj-y += idt.o
obj-y += recall.o
obj-y += traps.o

obj-y += pre_printk.o

extra-y += kernel.lds
clean-y += include/generated/
