# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += cpu/ device/ lock/
obj-y += irq/ sched/ time/
obj-y += task/ printk/ binfmt/
obj-y += crash.o sleep.o syscall.o
obj-y += resource.o power.o pevent.o
