obj-y += dbnames.o
obj-y += dbconvert.o
obj-y += dbmethod.o
obj-y += dbcmds.o
obj-y += dbxface.o
obj-y += dbdisply.o
obj-y += dbinput.o
obj-y += dbhistry.o
obj-y += dbexec.o
obj-y += dbstats.o
obj-y += dbutils.o
obj-y += dbobject.o

obj-n += dbfileio.o
obj-n += dbtest.o
