# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_UART_8250) += 8250.o

obj-$(CONFIG_UART_8250_CON) += 8250-con.o
obj-$(CONFIG_UART_8250_ISA) += 8250-isa.o
obj-$(CONFIG_UART_8250_PCI) += 8250-pci.o
