# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += libc/ font/
obj-y += rbtree.o list.o sort.o # hlist.o
obj-y += crc.o kfifo.o size.o

obj-$(CONFIG_ARCH_32BIT) += divdi3.o
obj-$(CONFIG_ACPI) += acpica/
obj-$(CONFIG_DT) += fdt/
