# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += libc/ font/ crypto/
obj-y += bitops.o bitmap.o ncache.o
obj-y += sort.o klist.o ilist.o
obj-y += rbtree.o idr.o kfifo.o
obj-y += param.o kasprintf.o
obj-y += size.o time.o librtc.o
obj-$(CONFIG_DEBUG_LIST) += list.o
obj-$(CONFIG_DEBUG_HLIST) += hlist.o
obj-$(CONFIG_DEBUG_SLIST) += slist.o
obj-$(CONFIG_DEBUG_REFCOUNT) += refcount.o
obj-$(CONFIG_ARCH_32BIT) += divdi3.o
obj-$(CONFIG_ACPI) += acpica/
obj-$(CONFIG_DT) += fdt/
