# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += libc/ font/ crypto/
obj-y += bitops.o bitmap.o ncache.o
obj-y += sort.o klist.o ilist.o
obj-y += rbtree.o idr.o
obj-y += kfifo.o bsearch.o
obj-y += param.o kasprintf.o
obj-y += time.o librtc.o
obj-y += size.o memdump.o
obj-$(CONFIG_DEBUG_LIST) += list-debug.o
obj-$(CONFIG_DEBUG_HLIST) += hlist-debug.o
obj-$(CONFIG_DEBUG_SLIST) += slist-debug.o
obj-$(CONFIG_DEBUG_RBTREE) += rbtree-debug.o
obj-$(CONFIG_DEBUG_REFCOUNT) += refcount.o
obj-$(CONFIG_ARCH_32BIT) += divdi3.o
obj-$(CONFIG_ACPI) += acpica/
obj-$(CONFIG_DT) += fdt/
