# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += init.o memblock.o kmalloc/
obj-y += page.o region.o model.o mempool.o
obj-y += vmem.o highmem.o pgalloc.o
obj-y += vmap.o ioremap.o vmalloc.o
obj-$(CONFIG_MEMTEST) += memtest.o
