# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile for Memory manager

obj-$(CONFIG_MMU) += page/
obj-y += kmem/

obj-y += resource.o
obj-y += ioremap.o 
obj-y += memblock.o
obj-y += memtest.o
obj-y += init.o