obj-y += clocksource/ irqchip/ 

obj-$(CONFIG_ACPI) += acpi/
obj-$(CONFIG_ATA) += ata/
obj-$(CONFIG_BLOCK) += block/
obj-$(CONFIG_CHAR) += char/
obj-$(CONFIG_CLK) += clk/
obj-$(CONFIG_CPUFREQ) += cpufreq/
obj-$(CONFIG_DT) += dt/
obj-$(CONFIG_FLOPPY) += floppy/
obj-$(CONFIG_GPIO) += gpio/
obj-$(CONFIG_I2C) += i2c/
obj-$(CONFIG_INPUT) += input/
obj-$(CONFIG_LED) += led/
obj-$(CONFIG_MTD) += mtd/
obj-$(CONFIG_PCI) += pci/
obj-$(CONFIG_NETD) += net/
obj-$(CONFIG_RTC) += rtc/
obj-$(CONFIG_MMC) += mmc/
obj-$(CONFIG_SND) += sound/
obj-$(CONFIG_THERMAL) += thermal/
obj-$(CONFIG_UART) += uart/
obj-$(CONFIG_USB) += usb/
obj-$(CONFIG_VIDEO) += video/
obj-$(CONFIG_WATCHDOG) += watchdog/
 
