obj-$(CONFIG_ARCH_ARM)      += arm/
obj-$(CONFIG_ARCH_ARM64)    += arm64/
obj-$(CONFIG_ARCH_ARME)     += arme/
obj-$(CONFIG_ARCH_CSKY)     += csky/
obj-$(CONFIG_ARCH_RISCV64)  += riscv64/
obj-$(CONFIG_ARCH_X86)      += x86/
obj-$(CONFIG_ARCH_XTENSA)   += xtensa/
