# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += delay.o
obj-$(CONFIG_CSKY_ABIV1) += memcpy-v1.o setjmp-v1.o
obj-$(CONFIG_CSKY_ABIV2) += memcmp-v2.o memcpy-v2.o memmove-v2.o
obj-$(CONFIG_CSKY_ABIV2) += memset-v2.o strcmp-v2.o strcpy-v2.o strlen-v2.o
