# SPDX-License-Identifier: GPL-2.0-or-later
ccflags-y := -Ofast
obj-$(CONFIG_LIBGCC_BASE) += libgcc.obj
obj-$(CONFIG_LIBGCC_DIVDI3) += divdi3.o
obj-$(CONFIG_LIBGCC_DIVSI3) += divsi3.o
obj-$(CONFIG_LIBGCC_DIVHI3) += divhi3.o
