#ifndef _DRIVER_ATA_H_
#define _DRIVER_ATA_H_

struct ata_ops {
    /* command */

};

enum ata_registers {
    ATA_REG_DATA        = 0x00,
    ATA_REG_ERR         = 0x01,
    ATA_REG_FEATURE     = 0x01,
    ATA_REG_NSECT       = 0x02,
    ATA_REG_IRQ         = 0x02,
    ATA_REG_LBAL        = 0x03,
    ATA_REG_LBAM        = 0x04,
    ATA_REG_BYTEL       = 0x04,
    ATA_REG_LBAH        = 0x05,
    ATA_REG_BYTEH		= 0x05,
    ATA_REG_DEVICE      = 0x06,
    ATA_REG_DEVSEL      = 0x06,
    ATA_REG_STATUS      = 0x07,
    ATA_REG_CMD         = 0x07,
};

enum ata_command {
    ATA_COMMAND_NOP                                     = 0x00,
    ATA_COMMAND_CFA_RESERVED0                           = 0X03,
    ATA_COMMAND_DATA_SET_MANAGEMENT                     = 0x06,
    ATA_COMMAND_DEVICE_RESET                            = 0x08,
    ATA_COMMAND_REQUEST_SENSE                           = 0x0B,
    ATA_COMMAND_RECALIBRATE                             = 0x10,
    ATA_COMMAND_READ_SECTORS_WITH_RETRY                 = 0x20,
    ATA_COMMAND_READ_SECTORS_WITHOUT_RETRY              = 0x21,
    ATA_COMMAND_READ_LONG_WITH_RETRY                    = 0x22,
    ATA_COMMAND_READ_LONG_WITHOUT_RETRY                 = 0x23,
    ATA_COMMAND_READ_SECTORS_EXT                        = 0x24,
    ATA_COMMAND_READ_DMA_EXT                            = 0x25,
    ATA_COMMAND_READ_DMA_QUEUED_EXT                     = 0x26,
    ATA_COMMAND_READ_NATIVE_MAX_ADDRESS_EXT             = 0x27,
    ATA_COMMAND_READ_MULTIPLE_EXT                       = 0x29,
    ATA_COMMAND_READ_STREAM_DMA                         = 0x2A,
    ATA_COMMAND_READ_STREAM                             = 0x2B,
    ATA_COMMAND_READ_LOG_EXT                            = 0x2F,
    ATA_COMMAND_WRITE_SECTORS_WITH_RETRY                = 0x30,
    ATA_COMMAND_WRITE_SECTORS_WITHOUT_RETRY             = 0x31,
    ATA_COMMAND_WRITE_LONG_WITH_RETRY                   = 0x32,
    ATA_COMMAND_WRITE_LONG_WITHOUT_RETRY                = 0x33,
    ATA_COMMAND_WRITE_SECTORS_EXT                       = 0x34,
    ATA_COMMAND_WRITE_DMA_EXT                           = 0x35,
    ATA_COMMAND_WRITE_DMA_QUEUED_EXT                    = 0x36,
    ATA_COMMAND_SET_NATIVE_MAX_ADDRESS_EXT              = 0x37,
    ATA_COMMAND_CFA_RESERVED1                           = 0x38,
    ATA_COMMAND_WRITE_MULTIPLE_EXT                      = 0x39,
    ATA_COMMAND_WRITE_STREAM_DMA                        = 0x3A,
    ATA_COMMAND_WRITE_STREAM                            = 0x3B,
    ATA_COMMAND_WRITE_VERIFY                            = 0x3C,
    ATA_COMMAND_WRITE_DMA_FUA_EXT                       = 0x3D,
    ATA_COMMAND_WRITE_DMA_QUEUED_FUA_EXT                = 0x3E,
    ATA_COMMAND_WRITE_LOG_EXT                           = 0x3F,
    ATA_COMMAND_READ_VERIFY_SECTORS_WITH_RETRY          = 0x40,
    ATA_COMMAND_READ_VERIFY_SECTORS_WITHOUT_RETRY       = 0x41,
    ATA_COMMAND_READ_VERIFY_SECTORS_EXT                 = 0x42,
    ATA_COMMAND_Trusted_Non_Data                        = 0x5B,
    ATA_COMMAND_Trusted_Receive                         = 0x5C,
    ATA_COMMAND_Trusted_Receive_DMA                     = 0x5D,
    ATA_COMMAND_Trusted_Send                            = 0x5E,
    ATA_COMMAND_Trusted_Send_DMA                        = 0x5F,
    ATA_COMMAND_Read_FPDMA_Queued                       = 0x60,
    ATA_COMMAND_Write_FPDMA_Queued                      = 0x61,
    ATA_COMMAND_SATA_Reserved0                          = 0x62,
    ATA_COMMAND_NCQ_Queue_Management                    = 0x63,
    ATA_COMMAND_Send_FPDMA_Queued                       = 0x64,
    ATA_COMMAND_Receive_FPDMA_Queued                    = 0x65,
    ATA_COMMAND_SATA_Reserved1                          = 0x66,
    ATA_COMMAND_SATA_Reserved2                          = 0x67,
    ATA_COMMAND_SEEK                                    = 0x70,
    ATA_COMMAND_SET_DATETIME_EXT                        = 0x77,
    ATA_COMMAND_ACCESSIBLE_MAX_ADDRESS_CONFIGURATION    = 0x78,
    ATA_COMMAND_SMART                                   = 0xB0,
    ATA_COMMAND_READ_DMA                                = 0xC8,
    ATA_COMMAND_WRITE_DMA                               = 0xCA,
    ATA_COMMAND_CACHE_FLUSH                             = 0xE7,
    ATA_COMMAND_CACHE_FLUSH_EXT                         = 0xEA,
    ATA_COMMAND_PACKET                                  = 0xA0,
    ATA_COMMAND_IDENTIFY_PACKET                         = 0xA1,
    ATA_COMMAND_IDENTIFY                                = 0xEC,
    ATA_COMMAND_GET_MEDIA_STATUS                        = 0xDA,
    ATA_COMMAND_ACKNOWLEDGE_MEDIA_CHANGE                = 0xDB,
    ATA_COMMAND_BOOT_POST_BOOT                          = 0xDC,
    ATA_COMMAND_BOOT_PRE_BOOT                           = 0xDD,
    ATA_COMMAND_MEDIA_LOCK                              = 0xDE,
    ATA_COMMAND_MEDIA_UNLOCK                            = 0xDF,
    ATA_COMMAND_STANDBY_IMMEDIATE                       = 0xE0,
    ATA_COMMAND_IDLE_IMMEDIATE                          = 0xE1,
    ATA_COMMAND_STANDBY                                 = 0xE2,
    ATA_COMMAND_IDLE                                    = 0xE3,
    ATA_COMMAND_READ_BUFFER                             = 0xE4,
    ATA_COMMAND_CHECK_POWER_MODE                        = 0xE5,
    ATA_COMMAND_SLEEP                                   = 0xE6,
    ATA_COMMAND_FLUSH_CACHE                             = 0xE7,
    ATA_COMMAND_WRITE_BUFFER                            = 0xE8,
    ATA_COMMAND_READ_BUFFER_DMA                         = 0xE9,
    ATA_COMMAND_FLUSH_CACHE_EXT                         = 0xEA,
    ATA_COMMAND_WRITE_BUFFER_DMA                        = 0xEB,
    ATA_COMMAND_IDENTIFY_DEVICE                         = 0xEC,
    ATA_COMMAND_MEDIA_EJECT                             = 0xED,
    ATA_COMMAND_IDENTIFY_DEVICE_DMA                     = 0xEE,
    ATA_COMMAND_SET_FEATURES                            = 0xEF,
    ATA_COMMAND_VENDOR_SPECIFIC                         = 0xF0,
    ATA_COMMAND_SECURITY_SET_PASSWORD                   = 0xF1,
    ATA_COMMAND_SECURITY_UNLOCK                         = 0xF2,
    ATA_COMMAND_SECURITY_ERASE_PREPARE                  = 0xF3,
    ATA_COMMAND_SECURITY_ERASE_UNIT                     = 0xF4,
    ATA_COMMAND_SECURITY_FREEZE_LOCK                    = 0xF5,
    ATA_COMMAND_SECURITY_DISABLE_PASSWORD               = 0xF6,
    ATA_COMMAND_READ_NATIVE_MAX_ADDRESS                 = 0xF8,
    ATA_COMMAND_SET_MAX_ADDRESS                         = 0xF9,
    ATA_COMMAND_VENDOR0                                 = 0xFA,
    ATA_COMMAND_VENDOR1                                 = 0xFB,
    ATA_COMMAND_VENDOR2                                 = 0xFC,
    ATA_COMMAND_VENDOR3                                 = 0xFD,
    ATA_COMMAND_VENDOR4                                 = 0xFE,
    ATA_COMMAND_VENDOR5                                 = 0xFF,
};

#define ATA_STATUS_BSY          0x80    /* Busy */
#define ATA_STATUS_DRDY         0x40    /* Drive ready */
#define ATA_STATUS_DF           0x20    /* Drive write fault */
#define ATA_STATUS_DSC          0x10    /* Drive seek complete */
#define ATA_STATUS_DRQ          0x08    /* Data request ready */
#define ATA_STATUS_CORR         0x04    /* Corrected data */
#define ATA_STATUS_IDX          0x02    /* Index */
#define ATA_STATUS_ERR          0x01    /* Error */


#endif /* _DRIVER_ATA_H_ */
