###
# scripts contains sources for various helper programs used throughout
# the kernel for the build process.
# ---------------------------------------------------------------------------
clean-subdir-y += basic/
clean-subdir-y += dtc/
clean-subdir-y += kconfig/
