# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_SELFTEST_KERNEL_KCORO) += kcoro.o
obj-$(CONFIG_SELFTEST_KERNEL_PRANDOM) += prandom.o
obj-$(CONFIG_SELFTEST_KERNEL_RANDOM) += random.o
obj-$(CONFIG_SELFTEST_KERNEL_SOFTIRQ) += softirq.o
obj-$(CONFIG_SELFTEST_KERNEL_SYSCALL) += syscall.o
obj-$(CONFIG_SELFTEST_KERNEL_TIMER) += timer.o
