/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright(c) 2022 Sanpe <sanpeqf@gmail.com>
 */

#include <manual.h>

DEFINE_MANUAL(shortcut,
    "NAME\n"
    "\tshortcut - shortcut keys of kshell\n"
    "\n"
    "DESCRIPTION\n"
    "\tCtrl+A:  Cursor Home\n"
    "\tCtrl+B:  Cursor Left\n"
    "\tCtrl+C:  Break Readline\n"
    "\tCtrl+D:  Delete\n"
    "\tCtrl+E:  Cursor End\n"
    "\tCtrl+F:  Cursor Right\n"
    "\tCtrl+G:  Beep Bell\n"
    "\tCtrl+H:  Backspace\n"
    "\tCtrl+I:  Complete\n"
    "\tCtrl+J:  Line Feed\n"
    "\tCtrl+K:  Clear After\n"
    "\tCtrl+L:  Form Feed\n"
    "\tCtrl+M:  Carriage Return\n"
    "\tCtrl+N:  History Complete Next\n"
    "\tCtrl+O:  Clipboard Select\n"
    "\tCtrl+P:  History Complete Prev\n"
    "\tCtrl+Q:  History Clear\n"
    "\tCtrl+R:  Clipboard Clear\n"
    "\tCtrl+S:  Readline Lock\n"
    "\tCtrl+T:  Repeat Execution\n"
    "\tCtrl+U:  Clear Before\n"
    "\tCtrl+V:  History Next\n"
    "\tCtrl+W:  History Prev\n"
    "\tCtrl+X:  Clipboard Cut\n"
    "\tCtrl+Y:  Clipboard Yank\n"
    "\tCtrl+Z:  Clipboard Paste\n"
    "\tAlt+b:   Backspace Word\n"
    "\tAlt+d:   Delete Word\n"
    "\tAlt+l:   Cursor Left Word\n"
    "\tAlt+r:   Cursor Right Word\n"
    "\n"
    "SPECIAL KEY\n"
    "\tBackspace            -> Ctrl+H\n"
    "\tAlt Backspace        -> Alt+b\n"
    "\tCursor Up            -> Ctrl+P\n"
    "\tCtrl Cursor Up       -> Ctrl+W\n"
    "\tCursor Down          -> Ctrl+N\n"
    "\tCtrl Cursor Down     -> Ctrl+V\n"
    "\tCursor Right         -> Ctrl+F\n"
    "\tCtrl Cursor Right    -> Alt+r\n"
    "\tCursor Left          -> Ctrl+B\n"
    "\tCtrl Cursor Left     -> Alt+l\n"
    "\tCursor Middle        -> Ctrl+T\n"
    "\tControl End          -> Ctrl+E\n"
    "\tCtrl Control End     -> Ctrl+K\n"
    "\tControl Home         -> Ctrl+A\n"
    "\tCtrl Control Home    -> Ctrl+U\n"
    "\tControl Insert       -> Ctrl+Z\n"
    "\tControl Delete       -> Ctrl+D\n"
    "\tControl Page Up      -> Ctrl+W\n"
    "\tControl Page Down    -> Ctrl+V\n"
    "\tAlt Control Insert   -> Ctrl+X\n"
    "\tCtrl Control Insert  -> Ctrl+Y\n"
    "\tAlt Control Insert   -> Ctrl+O\n"
    "\tCtrl Control Delete  -> Alt+d\n"
);
