obj-y += rsutils.o
obj-y += rsxface.o
obj-y += rsdumpinfo.o
obj-y += rsaddr.o
obj-y += rscreate.o
obj-y += rsmisc.o
obj-y += rscalc.o
obj-y += rslist.o
obj-y += rsmemory.o
obj-y += rsserial.o
obj-y += rsinfo.o
obj-y += rsirq.o
obj-y += rsio.o

obj-$(CONFIG_ACPI_DEBUG) += rsdump.o
