# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += core/ partitions/
obj-$(CONFIG_BLK_FLOPPY) += floppy.o
obj-$(CONFIG_BLK_AHCISIM) += simple-ahci.o
obj-$(CONFIG_BLK_ATASIM) += simple-ata.o
obj-$(CONFIG_BLK_NVMESIM) += simple-nvme.o
