# SPDX-License-Identifier: GPL-2.0-or-later
obj-y += base64.o ascii85.o aes.o
obj-y += chacha.o sha1.o sha256.o
obj-y += crc8.o crc16.o crc32.o
obj-y += crc-ccitt.o crc-ccittf.o
obj-y += crc-itut.o crc-t10dif.o